# import_required_colors "${REQUIRED_COLORS[@]}"

require_file "$(dirname "$0")/bash/install/Partitioninig_the_disk.sh"
require_file "$(dirname "$0")/bash/install/Formating_boot_partition.sh"
require_file "$(dirname "$0")/bash/install/Formating_Linux_system_partition.sh"
require_file "$(dirname "$0")/bash/install/Formating_root.sh"
require_file "$(dirname "$0")/bash/install/Making_swap.sh"
require_file "$(dirname "$0")/bash/install/Mirror_configuration.sh"
require_file "$(dirname "$0")/bash/install/Base_system_setup.sh"
require_file "$(dirname "$0")/bash/install/Configure_bootloader.sh"
require_file "$(dirname "$0")/bash/install/Setup_users.sh"
require_file "$(dirname "$0")/bash/install/Setup_network.sh"
require_file "$(dirname "$0")/bash/install/Setup_window_managers.sh"
require_file "$(dirname "$0")/bash/install/Enable_services.sh"
require_file "$(dirname "$0")/bash/install/CodexBox_setup.sh"
require_file "$(dirname "$0")/bash/install/Optional_package.sh"
require_file "$(dirname "$0")/bash/install/Flatpack_setup.sh"
require_file "$(dirname "$0")/bash/install/Snap_setup.sh"

#require_file "$(dirname "$0")/bash/install/"